# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4693ee37d4a57f5b2e3cd3d1060618e21da9fd07f58058ec20be6421987f971dff6541fc50cfd1c16986b012804d6f9e99baadbcba8b1b7c715634d9d11da42f

test:
  secret_key_base: 8a0ea59c91eee18c9cc9930963aff1ee73a7da6135fd6a35f977702d010dcd75f8ad2e87c8396cd5494d6fa60b1ae5443d35d72ae55b3b601ceebba40254eb94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
